/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QueryGUI.java
 *
 * Created on Jun 30, 2010, 10:23:56 PM
 */
package queryet;

import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import queryet.ServerObjects.MasterServerList;
import queryet.ServerObjects.ServerInfo;

/**
 *
 * @author mike
 */
public class QueryGUI extends javax.swing.JFrame {

    /** Creates new form QueryGUI */
    public QueryGUI() {
        initComponents();
//        propsTableModel.addColumn("Name");
//        propsTableModel.addColumn("Address");
//        propsTableModel.addColumn("Ping");
//        propsTableModel.addColumn("Players");
//        propsTableModel.addColumn("Map");
//        propsTableModel.addColumn("Game");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){

            public boolean isCellEditable(int row, int column) {
                return false; // change this to true to see the difference.
            }
        }
        ;
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QueryET");

        jButton1.setText("Update Servers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Connect");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(propsTableModel);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable1);

        jLabel1.setText("0 servers");
        jLabel1.setBorder(null);

        jMenu1.setText("File");

        jMenuItem2.setText("Quit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Preferences");
        jMenuItem1.setToolTipText("change settings");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("help");

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(759, Short.MAX_VALUE))
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(898, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        final ArrayList<MasterServerList> masters = QueryET.getListFromMaster();

        new Thread("UpdateButtonPushed") {

            @Override
            public void run() {

                int idx = 0;
                for (MasterServerList m : masters) {
                    //for testing...limits to 20 servers
//            if (idx < 20) {

                    ServerInfo s = QueryET.getServerInfo(m.getAddress(), m.getPort());

                    if (s.getPing() > 0) {
                        // name addr:port ping players map mode
                        Object[] add = {s.getName(), s.getAddress() + ":" + s.getPort(), s.getPing(), s.getCurrentPlayers() + "/" + s.getMaxPlayers(), s.getMap(), "5"};
                        propsTableModel.addRow(add);
                        idx++;
                    }
//            }
                }
            }
        }.start();


        jLabel1.setText(masters.size() + " servers");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //does nothing for now
//        LaunchET.startET("not used for now", );
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (evt.getActionCommand().equals("Quit")) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        System.out.println("click count: " + evt.getClickCount());
        JTable target = (JTable) evt.getSource();
        int row = target.getSelectedRow();
        int column = target.getSelectedColumn();

        if (evt.getComponent().isEnabled() && evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
            Point p = evt.getPoint();
//            int row = jTable1.rowAtPoint(p);
//            int column = jTable1.columnAtPoint(p);
            System.out.println("Launching ET...");
            System.out.println("Connecting to server: " + (String) jTable1.getValueAt(row, column));
            // "not used for now" IS JUST A PLACE HOLDER FOR NOW. ACTUAL BINARY IS HARD CODED INTO startET()
            System.out.println("row: " + row + " column: " + column);
            LaunchET.startET("/home/mike/et-sdl-sound", (String) jTable1.getValueAt(row, 1));
//        }


            // Use table.convertRowIndexToModel / table.convertColumnIndexToModle to convert to view indices

            // ...
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // launch about window
        if (evt.getActionCommand().equalsIgnoreCase("about")) {
            JFrame newFrame = new JFrame();
            newFrame.setTitle("Detail Screen");
            newFrame.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new QueryGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
//    private DefaultListModel lm1 = new DefaultListModel();
//    private DefaultListModel lm2 = new DefaultListModel();
//    private DefaultListModel lm3 = new DefaultListModel();
//    private DefaultListModel lm4 = new DefaultListModel();
//    private DefaultListModel lm5 = new DefaultListModel();
//    private DefaultListModel lm6 = new DefaultListModel();
//    private DefaultTableModel propsTableModel = new DefaultTableModel();
    String[] columns = {"Name", "Address", "Ping", "Players", "Map", "Game"};
    private CustomTableModel propsTableModel = new CustomTableModel(columns, 0);
}

class CustomTableModel extends DefaultTableModel {

    public CustomTableModel(Object[] columns, int rows) {
        super(columns, rows);
    }

    @Override
    public Class getColumnClass(int c) {
        return getValueAt(0, c).getClass();
    }

    @Override
    public boolean isCellEditable(int row, int col) {
        return false;
    }
}
